import Head from 'next/head'
import LandingPage from '../components/LandingPage'


export default function Home() {
  return (
    <div className='max-w-6xl'>
      <Head>
        <title>Primary Saving App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LandingPage/>
    </div>
  )
}
