import Head from 'next/head'
import LandingPage from '../components/LandingPage'
import { MainNav } from '../components/MainNav'
import { Footer } from '../components/Footer'


export default function Home() {
  return (
    <>
      <Head>
        <title>Primary Saving App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainNav />
      <LandingPage/>
      <div className="w-screen">
        <Footer />
      </div>

    </>
  )
}
