import Head from 'next/head'
import { LoginPage } from '../components/LoginPage'


export default function Home() {
  return (
    <>
      <Head>
        <title>Sign In - PrimarySaving</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen">
        <LoginPage />
      </div>


    </>
  )
}
