import Head from 'next/head'
import { RegisterPage } from '../components/RegisterPage'


export default function Home() {
  return (
    <>
      <Head>
        <title>Sign Up - PrimarySaving</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen">
        <RegisterPage />
      </div>


    </>
  )
}
